// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import {
    MobxModelElementImpl,
    observableprim,
    observablepart,
    type FreNamedNode,
    FreParseLocation,
    notNullOrUndefined,
    FreNodeReference,
    FreUtils,
} from "@freon4dsl/core";
import { type Type } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate
import { makeObservable, action } from "mobx";

/**
 * Class PropertyDef is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class PropertyDef extends MobxModelElementImpl implements FreNamedNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<PropertyDef>): PropertyDef {
        const result = new PropertyDef(data.$id);
        if (notNullOrUndefined(data.name)) {
            result.name = data.name;
        }
        if (notNullOrUndefined(data.mayBeNull)) {
            result.mayBeNull = data.mayBeNull;
        }
        if (notNullOrUndefined(data.isList)) {
            result.isList = data.isList;
        }
        if (notNullOrUndefined(data.isOptional)) {
            result.isOptional = data.isOptional;
        }
        if (notNullOrUndefined(data.type)) {
            result.type = data.type;
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "PropertyDef"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed
    name!: string; // implementation of name
    mayBeNull!: boolean; // implementation of mayBeNull
    isList!: boolean; // implementation of isList
    isOptional!: boolean; // implementation of isOptional

    type!: FreNodeReference<Type>; // implementation of reference 'type'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }
        // Both 'observableprim' and 'observableprimlist' change the get and set of the attribute
        // such that the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observableprim(this, "name");
        this.name = "";
        observableprim(this, "mayBeNull");
        this.mayBeNull = false;
        observableprim(this, "isList");
        this.isList = false;
        observableprim(this, "isOptional");
        this.isOptional = false;

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepart(this, "type");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): PropertyDef {
        const result = new PropertyDef();
        if (notNullOrUndefined(this.name)) {
            result.name = this.name;
        }
        if (notNullOrUndefined(this.mayBeNull)) {
            result.mayBeNull = this.mayBeNull;
        }
        if (notNullOrUndefined(this.isList)) {
            result.isList = this.isList;
        }
        if (notNullOrUndefined(this.isOptional)) {
            result.isOptional = this.isOptional;
        }
        if (notNullOrUndefined(this.type)) {
            result.type = this.type.copy();
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<PropertyDef>): boolean {
        let result: boolean = true;
        if (result && toBeMatched.name !== null && toBeMatched.name !== undefined && toBeMatched.name.length > 0) {
            result = result && this.name === toBeMatched.name;
        }
        if (result && toBeMatched.mayBeNull !== null && toBeMatched.mayBeNull !== undefined) {
            result = result && this.mayBeNull === toBeMatched.mayBeNull;
        }
        if (result && toBeMatched.isList !== null && toBeMatched.isList !== undefined) {
            result = result && this.isList === toBeMatched.isList;
        }
        if (result && toBeMatched.isOptional !== null && toBeMatched.isOptional !== undefined) {
            result = result && this.isOptional === toBeMatched.isOptional;
        }
        if (result && notNullOrUndefined(toBeMatched.type)) {
            result = result && this.type.match(toBeMatched.type);
        }
        return result;
    }

    /**
     * Convenience method for reference 'type'.
     * Instead of returning a 'FreNodeReference<Type>' object,
     * it returns the referred 'Type' object, if it can be found.
     */
    get $type(): Type | undefined {
        if (!!this.type) {
            return this.type.referred;
        }
        return undefined;
    }
}
