// Generated by the Freon Language Generator.
// Generated by Freon LanguageTemplate

import {
    FreLanguage,
    type FreLanguageModel,
    type FreLanguageModelUnit,
    type FreLanguageProperty,
    type FreLanguageConcept,
    type FreLanguageInterface,
    FreNodeReference,
} from "@freon4dsl/core";

// Import as MyLanguage to avoid naming conflicts in generated constructors
import * as MyLanguage from "./internal.js";
import { ProtocolStdlib } from "../stdlib/ProtocolStdlib.js";

/**
 * Creates an in-memory representation of structure of the language metamodel, used in e.g. the (de)serializer.
 */
export function initializeLanguage() {
    FreLanguage.getInstance().name = "Protocol";
    FreLanguage.getInstance().languageVersion = "1";
    FreLanguage.getInstance().id = "";
    FreLanguage.getInstance().addModel(describeProtocol());
    FreLanguage.getInstance().addUnit(describeTypes());
    FreLanguage.getInstance().addUnit(describeMessageGroup());
    FreLanguage.getInstance().addConcept(describePropertyDef());
    FreLanguage.getInstance().addConcept(describePrimitiveType());
    FreLanguage.getInstance().addConcept(describeObjectType());
    FreLanguage.getInstance().addInterface(describeType());
    FreLanguage.getInstance().addReferenceCreator((name: string, type: string) => {
        return !!name ? FreNodeReference.create(name, type) : null;
    });
    FreLanguage.getInstance().stdLib = ProtocolStdlib.getInstance();
}

function describeProtocol(): FreLanguageModel {
    const model: FreLanguageModel<MyLanguage.Protocol> = {
        typeName: "Protocol",
        id: "-id-Protocol",
        key: "-key-Protocol",
        isNamespace: true,
        language: "-key-protocol",
        constructor: (id?: string) => {
            return new MyLanguage.Protocol(id);
        },
        creator: (data: Partial<MyLanguage.Protocol>) => {
            return MyLanguage.Protocol.create(data);
        },
        properties: new Map<string, FreLanguageProperty>(),
    };
    model.properties.set("name", {
        name: "name",
        id: "-id-Protocol-name",
        key: "-key-Protocol-name",
        type: "string",
        isList: false,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    model.properties.set("categories", {
        name: "categories",
        id: "-id-Protocol-categories",
        key: "-key-Protocol-categories",
        type: "MessageGroup",
        isList: true,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "part",
    });
    model.properties.set("typeDefinitions", {
        name: "typeDefinitions",
        id: "-id-Protocol-typeDefinitions",
        key: "-key-Protocol-typeDefinitions",
        type: "Types",
        isList: true,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "part",
    });

    // Type cast is here to avoid function-parameter variance issue:
    // function parameters are contravariant: a function that
    // accepts a more specific param is not assignable to one
    // that claims it can accept a broader param.
    return model as unknown as FreLanguageModel;
}

function describeTypes(): FreLanguageModelUnit {
    const modelunit: FreLanguageModelUnit<MyLanguage.Types> = {
        typeName: "Types",
        id: "-id-Types",
        key: "-key-Types",
        isNamedElement: true,
        isNamespace: false,
        language: "-key-protocol",
        fileExtension: "typ",
        subConceptNames: [], // Nothing yet, but may change in the future
        constructor: (id?: string) => {
            return new MyLanguage.Types(id);
        },
        creator: (data: Partial<MyLanguage.Types>) => {
            return MyLanguage.Types.create(data);
        },
        properties: new Map<string, FreLanguageProperty>(),
        trigger: "Types",
    };
    modelunit.properties.set("name", {
        name: "name",
        id: "-id-Types-name",
        key: "-key-Types-name",
        type: "string",
        isList: false,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    modelunit.properties.set("primitiveTypes", {
        name: "primitiveTypes",
        id: "-id-Types-primitiveTypes",
        key: "-key-Types-primitiveTypes",
        type: "PrimitiveType",
        isList: true,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "part",
    });
    modelunit.properties.set("objectTypes", {
        name: "objectTypes",
        id: "-id-Types-objectTypes",
        key: "-key-Types-objectTypes",
        type: "ObjectType",
        isList: true,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "part",
    });

    // Type cast is here to avoid function-parameter variance issue:
    // function parameters are contravariant: a function that
    // accepts a more specific param is not assignable to one
    // that claims it can accept a broader param.
    return modelunit as unknown as FreLanguageModelUnit;
}

function describeMessageGroup(): FreLanguageModelUnit {
    const modelunit: FreLanguageModelUnit<MyLanguage.MessageGroup> = {
        typeName: "MessageGroup",
        id: "-id-MessageGroup",
        key: "-key-MessageGroup",
        isNamedElement: true,
        isNamespace: false,
        language: "-key-protocol",
        fileExtension: "mes",
        subConceptNames: [], // Nothing yet, but may change in the future
        constructor: (id?: string) => {
            return new MyLanguage.MessageGroup(id);
        },
        creator: (data: Partial<MyLanguage.MessageGroup>) => {
            return MyLanguage.MessageGroup.create(data);
        },
        properties: new Map<string, FreLanguageProperty>(),
        trigger: "MessageGroup",
    };
    modelunit.properties.set("taggedUnionProperty", {
        name: "taggedUnionProperty",
        id: "-id-MessageGroup-taggedUnionProperty",
        key: "-key-MessageGroup-taggedUnionProperty",
        type: "string",
        isList: false,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    modelunit.properties.set("name", {
        name: "name",
        id: "-id-Type-name",
        key: "-key-Type-name",
        type: "string",
        isList: false,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    modelunit.properties.set("messages", {
        name: "messages",
        id: "-id-MessageGroup-messages",
        key: "-key-MessageGroup-messages",
        type: "ObjectType",
        isList: true,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "part",
    });
    modelunit.properties.set("sharedProperties", {
        name: "sharedProperties",
        id: "-id-MessageGroup-sharedProperties",
        key: "-key-MessageGroup-sharedProperties",
        type: "PropertyDef",
        isList: true,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "part",
    });

    // Type cast is here to avoid function-parameter variance issue:
    // function parameters are contravariant: a function that
    // accepts a more specific param is not assignable to one
    // that claims it can accept a broader param.
    return modelunit as unknown as FreLanguageModelUnit;
}

function describePropertyDef(): FreLanguageConcept {
    const concept: FreLanguageConcept<MyLanguage.PropertyDef> = {
        typeName: "PropertyDef",
        id: "-id-PropertyDef",
        key: "-key-PropertyDef",
        isAbstract: false,
        isPublic: true,
        isLimited: false,
        isNamespace: false,
        instanceNames: [],
        language: "-key-protocol",
        isNamedElement: true,
        trigger: "PropertyDef",
        constructor: (id?: string) => {
            return new MyLanguage.PropertyDef(id);
        },
        creator: (data: Partial<MyLanguage.PropertyDef>) => {
            return MyLanguage.PropertyDef.create(data);
        },
        properties: new Map<string, FreLanguageProperty>(),
        baseName: undefined,
        subConceptNames: [],
    };
    concept.properties.set("name", {
        name: "name",
        id: "-id-PropertyDef-name",
        key: "-key-PropertyDef-name",
        type: "string",
        isList: false,
        isOptional: false,
        isPublic: true,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    concept.properties.set("mayBeNull", {
        name: "mayBeNull",
        id: "-id-PropertyDef-mayBeNull",
        key: "-key-PropertyDef-mayBeNull",
        type: "boolean",
        isList: false,
        isOptional: false,
        isPublic: true,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    concept.properties.set("isList", {
        name: "isList",
        id: "-id-PropertyDef-isList",
        key: "-key-PropertyDef-isList",
        type: "boolean",
        isList: false,
        isOptional: false,
        isPublic: true,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    concept.properties.set("isOptional", {
        name: "isOptional",
        id: "-id-PropertyDef-isOptional",
        key: "-key-PropertyDef-isOptional",
        type: "boolean",
        isList: false,
        isOptional: false,
        isPublic: true,
        language: "-key-protocol",
        propertyKind: "primitive",
    });

    concept.properties.set("type", {
        name: "type",
        id: "-id-PropertyDef-type",
        key: "-key-PropertyDef-type",
        type: "Type",
        isList: false,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "reference",
    });
    // Type cast is here to avoid function-parameter variance issue:
    // function parameters are contravariant: a function that
    // accepts a more specific param is not assignable to one
    // that claims it can accept a broader param.
    return concept as unknown as FreLanguageConcept;
}

function describePrimitiveType(): FreLanguageConcept {
    const concept: FreLanguageConcept<MyLanguage.PrimitiveType> = {
        typeName: "PrimitiveType",
        id: "-id-PrimitiveType",
        key: "-key-PrimitiveType",
        isAbstract: false,
        isPublic: true,
        isLimited: false,
        isNamespace: false,
        instanceNames: [],
        language: "-key-protocol",
        isNamedElement: true,
        trigger: "PrimitiveType",
        constructor: (id?: string) => {
            return new MyLanguage.PrimitiveType(id);
        },
        creator: (data: Partial<MyLanguage.PrimitiveType>) => {
            return MyLanguage.PrimitiveType.create(data);
        },
        properties: new Map<string, FreLanguageProperty>(),
        baseName: undefined,
        subConceptNames: [],
    };
    concept.properties.set("primitiveType", {
        name: "primitiveType",
        id: "-id-PrimitiveType-primitiveType",
        key: "-key-PrimitiveType-primitiveType",
        type: "string",
        isList: false,
        isOptional: false,
        isPublic: true,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    concept.properties.set("validator", {
        name: "validator",
        id: "-id-PrimitiveType-validator",
        key: "-key-PrimitiveType-validator",
        type: "string",
        isList: false,
        isOptional: false,
        isPublic: true,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    concept.properties.set("name", {
        name: "name",
        id: "-id-Type-name",
        key: "-key-Type-name",
        type: "string",
        isList: false,
        isOptional: false,
        isPublic: true,
        language: "-key-protocol",
        propertyKind: "primitive",
    });

    // Type cast is here to avoid function-parameter variance issue:
    // function parameters are contravariant: a function that
    // accepts a more specific param is not assignable to one
    // that claims it can accept a broader param.
    return concept as unknown as FreLanguageConcept;
}

function describeObjectType(): FreLanguageConcept {
    const concept: FreLanguageConcept<MyLanguage.ObjectType> = {
        typeName: "ObjectType",
        id: "-id-ObjectType",
        key: "-key-ObjectType",
        isAbstract: false,
        isPublic: true,
        isLimited: false,
        isNamespace: false,
        instanceNames: [],
        language: "-key-protocol",
        isNamedElement: true,
        trigger: "ObjectType",
        constructor: (id?: string) => {
            return new MyLanguage.ObjectType(id);
        },
        creator: (data: Partial<MyLanguage.ObjectType>) => {
            return MyLanguage.ObjectType.create(data);
        },
        properties: new Map<string, FreLanguageProperty>(),
        baseName: undefined,
        subConceptNames: [],
    };
    concept.properties.set("name", {
        name: "name",
        id: "-id-Type-name",
        key: "-key-Type-name",
        type: "string",
        isList: false,
        isOptional: false,
        isPublic: true,
        language: "-key-protocol",
        propertyKind: "primitive",
    });
    concept.properties.set("properties", {
        name: "properties",
        id: "-id-ObjectType-properties",
        key: "-key-ObjectType-properties",
        type: "PropertyDef",
        isList: true,
        isPublic: true,
        isOptional: false,
        language: "-key-protocol",
        propertyKind: "part",
    });

    // Type cast is here to avoid function-parameter variance issue:
    // function parameters are contravariant: a function that
    // accepts a more specific param is not assignable to one
    // that claims it can accept a broader param.
    return concept as unknown as FreLanguageConcept;
}

function describeType(): FreLanguageInterface {
    const intface: FreLanguageInterface = {
        typeName: "Type",
        id: "-id-Type",
        key: "-key-Type",
        isPublic: true,
        isNamedElement: true,
        isNamespace: false,
        properties: new Map<string, FreLanguageProperty>(),
        language: "protocol",
        subConceptNames: ["PrimitiveType", "ObjectType", "MessageGroup"],
    };
    intface.properties.set("name", {
        name: "name",
        id: "-id-Type-name",
        key: "-key-Type-name",
        type: "string",
        isList: false,
        isPublic: true,
        isOptional: false,
        language: "protocol",
        propertyKind: "primitive",
    });

    // Type cast is here to avoid function-parameter variance issue:
    // function parameters are contravariant: a function that
    // accepts a more specific param is not assignable to one
    // that claims it can accept a broader param.
    return intface as unknown as FreLanguageConcept;
}
