// Generated by the Freon Language Generator.
import {
    MobxModelElementImpl,
    observableprim,
    observablepartlist,
    type FreModel,
    FreLanguage,
    FreParseLocation,
    type FreModelUnit,
    AST,
    notNullOrUndefined,
    FreUtils,
    matchElementList,
} from "@freon4dsl/core";
import { MessageGroup, Types } from "./internal.js";

import { makeObservable, action, runInAction } from "mobx";

/**
 * Class Protocol is the implementation of the model with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to any changes in the state of its properties.
 */
export class Protocol extends MobxModelElementImpl implements FreModel {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<Protocol>): Protocol {
        const result = new Protocol(data.$id);
        if (notNullOrUndefined(data.name)) {
            result.name = data.name;
        }
        if (notNullOrUndefined(data.categories)) {
            data.categories.forEach((x) => result.categories.push(x));
        }
        if (notNullOrUndefined(data.typeDefinitions)) {
            data.typeDefinitions.forEach((x) => result.typeDefinitions.push(x));
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "Protocol"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed
    name!: string; // implementation of name
    categories!: MessageGroup[]; // implementation of part 'categories'
    typeDefinitions!: Types[]; // implementation of part 'typeDefinitions'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepartlist(this, "categories");
        observablepartlist(this, "typeDefinitions");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return true;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): Protocol {
        const result = new Protocol();
        if (notNullOrUndefined(this.name)) {
            result.name = this.name;
        }
        if (notNullOrUndefined(this.categories)) {
            this.categories.forEach((x) => result.categories.push(x.copy()));
        }
        if (notNullOrUndefined(this.typeDefinitions)) {
            this.typeDefinitions.forEach((x) => result.typeDefinitions.push(x.copy()));
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<Protocol>): boolean {
        let result: boolean = true;
        if (result && toBeMatched.name !== null && toBeMatched.name !== undefined && toBeMatched.name.length > 0) {
            result = result && this.name === toBeMatched.name;
        }
        if (result && notNullOrUndefined(toBeMatched.categories)) {
            result = result && matchElementList(this.categories, toBeMatched.categories);
        }
        if (result && notNullOrUndefined(toBeMatched.typeDefinitions)) {
            result = result && matchElementList(this.typeDefinitions, toBeMatched.typeDefinitions);
        }
        return result;
    }

    /**
     * A convenience method that finds a unit of this model based on its name and 'metatype'.
     * @param name
     * @param metatype
     */
    findUnit(name: string, metatype?: string): FreModelUnit | undefined {
        let result: FreModelUnit | undefined;
        const checkType = metatype !== undefined;
        result = this.getUnits().find(
            (mod) => mod.name === name && (checkType ? FreLanguage.getInstance().metaConformsToType(mod, metatype) : true),
        );
        if (!!result) {
            return result;
        }
        return undefined;
    }

    /**
     * Adds a model unit. Returns false if anything goes wrong.
     *
     * @param newUnit
     */
    addUnit(newUnit: FreModelUnit): boolean {
        if (!!newUnit) {
            const myMetatype = newUnit.freLanguageConcept();
            switch (myMetatype) {
                case "MessageGroup": {
                    AST.changeNamed("addUnit", () => {
                        this.categories.push(newUnit as MessageGroup);
                    });
                    return true;
                }
                case "Types": {
                    AST.changeNamed("addUnit", () => {
                        this.typeDefinitions.push(newUnit as Types);
                    });
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Removes a model unit. Returns false if anything goes wrong.
     *
     * @param oldUnit
     */
    removeUnit(oldUnit: FreModelUnit): boolean {
        if (!!oldUnit) {
            const myMetatype = oldUnit.freLanguageConcept();
            switch (myMetatype) {
                case "MessageGroup": {
                    AST.changeNamed("removeUnit", () => {
                        this.categories.splice(this.categories.indexOf(oldUnit as MessageGroup), 1);
                    });
                    return true;
                }
                case "Types": {
                    AST.changeNamed("removeUnit", () => {
                        this.typeDefinitions.splice(this.typeDefinitions.indexOf(oldUnit as Types), 1);
                    });
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Returns an empty model unit of type 'typeName' within 'model'.
     * Returns undefined when the given 'typename' does not match any of the unit types
     * known in the language.
     *
     * @param typename
     */
    newUnit(typename: string): FreModelUnit | undefined {
        switch (typename) {
            case "MessageGroup": {
                let unit: MessageGroup | undefined;
                runInAction(() => {
                    unit = MessageGroup.create({});
                });
                if (!unit) throw new Error("Failed to create MessageGroup");
                AST.changeNamed("newUnit", () => {
                    this.categories.push(unit as MessageGroup);
                });
                return unit;
            }
            case "Types": {
                let unit: Types | undefined;
                runInAction(() => {
                    unit = Types.create({});
                });
                if (!unit) throw new Error("Failed to create Types");
                AST.changeNamed("newUnit", () => {
                    this.typeDefinitions.push(unit as Types);
                });
                return unit;
            }
        }
        return undefined;
    }

    /**
     * Returns a list of model units.
     */
    getUnits(): FreModelUnit[] {
        let result: FreModelUnit[] = [];
        result = result.concat(this.categories);
        result = result.concat(this.typeDefinitions);
        return result;
    }

    /**
     * Returns a list of model units of type 'type'.
     */
    getUnitsForType(type: string): FreModelUnit[] {
        switch (type) {
            case "MessageGroup": {
                return this.categories;
            }
            case "Types": {
                return this.typeDefinitions;
            }
        }
        return [];
    }
}
