// Generated by the Freon Language Generator.
// TEMPLATE: InterfaceTemplate.generateInterface

import { type FreNode } from "@freon4dsl/core";

/**
 * Interface Type is the implementation of the interface with the same name in the language definition file.
 */
export interface Type extends FreNode {
    name: string; // implementation of name

    copy(): Type;
}
