// Generated by the Freon Language Generator.
// TEMPLATE: UnitTemplate.generateUnit(...)

import {
    MobxModelElementImpl,
    observableprim,
    observablepartlist,
    type FreModelUnit,
    FreParseLocation,
    notNullOrUndefined,
    FreUtils,
    matchElementList,
} from "@freon4dsl/core";
import { PrimitiveType, ObjectType } from "./internal.js";

import { makeObservable, action } from "mobx";

/**
 * Class Types is the implementation of the model unit with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to any changes in the state of its properties.
 */
export class Types extends MobxModelElementImpl implements FreModelUnit {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<Types>): Types {
        const result = new Types(data.$id);
        if (notNullOrUndefined(data.name)) {
            result.name = data.name;
        }
        if (notNullOrUndefined(data.primitiveTypes)) {
            data.primitiveTypes.forEach((x) => result.primitiveTypes.push(x));
        }
        if (notNullOrUndefined(data.objectTypes)) {
            data.objectTypes.forEach((x) => result.objectTypes.push(x));
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    fileExtension: string = "";
    readonly $typename: string = "Types"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed
    name!: string; // implementation of name
    primitiveTypes!: PrimitiveType[]; // implementation of part 'primitiveTypes'
    objectTypes!: ObjectType[]; // implementation of part 'objectTypes'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }
        // Both 'observableprim' and 'observableprimlist' change the get and set of the attribute
        // such that the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observableprim(this, "name");
        this.name = "";

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepartlist(this, "primitiveTypes");
        observablepartlist(this, "objectTypes");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return true;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): Types {
        const result = new Types();
        if (notNullOrUndefined(this.name)) {
            result.name = this.name;
        }
        if (notNullOrUndefined(this.primitiveTypes)) {
            this.primitiveTypes.forEach((x) => result.primitiveTypes.push(x.copy()));
        }
        if (notNullOrUndefined(this.objectTypes)) {
            this.objectTypes.forEach((x) => result.objectTypes.push(x.copy()));
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<Types>): boolean {
        let result: boolean = true;
        if (result && toBeMatched.name !== null && toBeMatched.name !== undefined && toBeMatched.name.length > 0) {
            result = result && this.name === toBeMatched.name;
        }
        if (result && notNullOrUndefined(toBeMatched.primitiveTypes)) {
            result = result && matchElementList(this.primitiveTypes, toBeMatched.primitiveTypes);
        }
        if (result && notNullOrUndefined(toBeMatched.objectTypes)) {
            result = result && matchElementList(this.objectTypes, toBeMatched.objectTypes);
        }
        return result;
    }
}
