// Generated by the Freon Language Generator.
// TEMPLATE: NonOptionalsCheckerTemplate.generateChecker(...)

import { FreError, FreErrorSeverity, type FreWriter, FreLanguageEnvironment, isNullOrUndefined } from "@freon4dsl/core";
import { Protocol, MessageGroup, Types, PropertyDef, PrimitiveType, ObjectType } from "../language/index.js";

import { ProtocolDefaultWorker } from "../utils/index.js";
import { type ProtocolCheckerInterface } from "./ProtocolValidator.js";
import { locationDescription } from "../../custom/CustomLocationDescription.js";

/**
 * Class ProtocolNonOptionalsChecker is part of the implementation of the default validator.
 * It checks whether non-optional properties, as such defined in the .ast definition, indeed
 * have a value.
 * Class ProtocolWalker implements the traversal of the model tree. This class implements
 * the actual checking of each node in the tree.
 */
export class ProtocolNonOptionalsChecker extends ProtocolDefaultWorker implements ProtocolCheckerInterface {
    // 'myWriter' is used to provide error messages on the nodes in the model tree
    myWriter: FreWriter = FreLanguageEnvironment.getInstance().writer;
    // 'errorList' holds the errors found while traversing the model tree
    errorList: FreError[] = [];

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeProtocol(node: Protocol): boolean {
        if (isNullOrUndefined(node.name) || node.name?.length === 0) {
            this.errorList.push(
                new FreError(`Property 'name' of ${locationDescription(node)} must have a value`, node, "name", FreErrorSeverity.Error),
            );
        }

        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeMessageGroup(node: MessageGroup): boolean {
        if (isNullOrUndefined(node.taggedUnionProperty) || node.taggedUnionProperty?.length === 0) {
            this.errorList.push(
                new FreError(
                    `Property 'taggedUnionProperty' of ${locationDescription(node)} must have a value`,
                    node,
                    "taggedUnionProperty",
                    FreErrorSeverity.Error,
                ),
            );
        }
        if (isNullOrUndefined(node.name) || node.name?.length === 0) {
            this.errorList.push(
                new FreError(`Property 'name' of ${locationDescription(node)} must have a value`, node, "name", FreErrorSeverity.Error),
            );
        }

        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTypes(node: Types): boolean {
        if (isNullOrUndefined(node.name) || node.name?.length === 0) {
            this.errorList.push(
                new FreError(`Property 'name' of ${locationDescription(node)} must have a value`, node, "name", FreErrorSeverity.Error),
            );
        }

        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePropertyDef(node: PropertyDef): boolean {
        if (isNullOrUndefined(node.name) || node.name?.length === 0) {
            this.errorList.push(
                new FreError(`Property 'name' of ${locationDescription(node)} must have a value`, node, "name", FreErrorSeverity.Error),
            );
        }
        if (isNullOrUndefined(node.mayBeNull)) {
            this.errorList.push(
                new FreError(
                    `Property 'mayBeNull' of ${locationDescription(node)} must have a value`,
                    node,
                    "mayBeNull",
                    FreErrorSeverity.Error,
                ),
            );
        }
        if (isNullOrUndefined(node.isList)) {
            this.errorList.push(
                new FreError(`Property 'isList' of ${locationDescription(node)} must have a value`, node, "isList", FreErrorSeverity.Error),
            );
        }
        if (isNullOrUndefined(node.isOptional)) {
            this.errorList.push(
                new FreError(
                    `Property 'isOptional' of ${locationDescription(node)} must have a value`,
                    node,
                    "isOptional",
                    FreErrorSeverity.Error,
                ),
            );
        }
        if (isNullOrUndefined(node.type)) {
            this.errorList.push(
                new FreError(`Property 'type' of ${locationDescription(node)} must have a value`, node, "type", FreErrorSeverity.Error),
            );
        }

        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePrimitiveType(node: PrimitiveType): boolean {
        if (isNullOrUndefined(node.primitiveType) || node.primitiveType?.length === 0) {
            this.errorList.push(
                new FreError(
                    `Property 'primitiveType' of ${locationDescription(node)} must have a value`,
                    node,
                    "primitiveType",
                    FreErrorSeverity.Error,
                ),
            );
        }
        if (isNullOrUndefined(node.validator) || node.validator?.length === 0) {
            this.errorList.push(
                new FreError(
                    `Property 'validator' of ${locationDescription(node)} must have a value`,
                    node,
                    "validator",
                    FreErrorSeverity.Error,
                ),
            );
        }
        if (isNullOrUndefined(node.name) || node.name?.length === 0) {
            this.errorList.push(
                new FreError(`Property 'name' of ${locationDescription(node)} must have a value`, node, "name", FreErrorSeverity.Error),
            );
        }

        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeObjectType(node: ObjectType): boolean {
        if (isNullOrUndefined(node.name) || node.name?.length === 0) {
            this.errorList.push(
                new FreError(`Property 'name' of ${locationDescription(node)} must have a value`, node, "name", FreErrorSeverity.Error),
            );
        }

        return false;
    }
}
