// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateValidator(...)

import { type FreValidator, FreError, type FreTyper, type FreNode } from "@freon4dsl/core";

import { ProtocolWalker, type ProtocolWorker } from "../utils/index.js";
import { ProtocolNonOptionalsChecker } from "./ProtocolNonOptionalsChecker.js";
import { ProtocolNamespaceChecker } from "./ProtocolNamespaceChecker.js";

import { ProtocolReferenceChecker } from "./ProtocolReferenceChecker.js";
import { freonConfiguration } from "../../custom/FreonConfiguration.js";

/**
 * Interface 'ProtocolCheckerInterface' represents any object that traverses the model tree and checks
 * its nodes, where any errors are deposited in 'errorList'.
 * Every checker that is used by the validator 'ProtocolValidator' should implement this interface.
 */
export interface ProtocolCheckerInterface extends ProtocolWorker {
    errorList: FreError[];
}

/**
 * Class ProtocolValidator implements the validator generated from, if present, the validator definition,
 * otherwise this class implements the default validator.
 * The implementation uses the visitor pattern to traverse the tree. Class ProtocolWalker implements
 * the actual checking of each node in the tree.
 */
export class ProtocolValidator implements FreValidator {
    /**
     * Returns the list of errors found in 'node'.
     * This method uses the visitor pattern to traverse the tree with 'node' as top node,
     * where classes ProtocolNonOptionalsChecker, ProtocolReferenceChecker,  implements the actual checking of each node in the tree.
     *
     * @param node
     * @param includeChildren if true, the children of 'node' are also checked.
     * The default for 'includeChildren' is true.
     */
    public validate(node: FreNode, includeChildren: boolean = true): FreError[] {
        // initialize the errorList
        const errorList: FreError[] = [];

        // create the walker over the model tree
        const myWalker = new ProtocolWalker();

        // create the checker on non-optional parts
        let myChecker = new ProtocolNonOptionalsChecker();
        myChecker.errorList = errorList;
        // and add the checker to the walker
        myWalker.myWorkers.push(myChecker);

        // create the checker on references
        myChecker = new ProtocolReferenceChecker();
        myChecker.errorList = errorList;
        // and add the checker to the walker
        myWalker.myWorkers.push(myChecker);

        // create the checker on (double names in) namespaces
        myChecker = new ProtocolNamespaceChecker();
        myChecker.errorList = errorList;
        // and add the checker to the walker
        myWalker.myWorkers.push(myChecker);

        // add any custom validations
        for (let checker of freonConfiguration.customValidations) {
            checker.errorList = errorList;
            myWalker.myWorkers.push(checker);
        }

        // do the work
        myWalker.walk(node, () => {
            return includeChildren;
        });

        // return any errors
        return errorList;
    }
}
