// Generated by the Freon Language Generator.
// TEMPLATE: NamespaceCheckerTemplate.generateChecker(...)

import {
    FreError,
    FreErrorSeverity,
    type FreWriter,
    FreLanguageEnvironment,
    FreLanguage,
    FreNamespace,
    type FreNode,
    type FreNamedNode,
    notNullOrUndefined,
} from "@freon4dsl/core";
import { Protocol, Types, MessageGroup, PropertyDef, PrimitiveType, ObjectType } from "../language/index.js";

import { ProtocolDefaultWorker } from "../utils/index.js";
import { type ProtocolCheckerInterface } from "./ProtocolValidator.js";

/**
 * Class ProtocolNamespaceChecker is part of the implementation of the default validator.
 * It checks whether namespaces, as such defined in the .scope definition, have more than one node
 * with the same name.
 * Class ProtocolWalker implements the traversal of the model tree. This class implements
 * the actual checking of each node in the tree.
 */
export class ProtocolNamespaceChecker extends ProtocolDefaultWorker implements ProtocolCheckerInterface {
    // 'myWriter' is used to provide error messages on the nodes in the model tree
    myWriter: FreWriter = FreLanguageEnvironment.getInstance().writer;
    // 'errorList' holds the errors found while traversing the model tree
    errorList: FreError[] = [];

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorlist'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeProtocol(node: Protocol): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Protocol")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorlist'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTypes(node: Types): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Types")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorlist'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeMessageGroup(node: MessageGroup): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("MessageGroup")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorlist'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePropertyDef(node: PropertyDef): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PropertyDef")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorlist'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePrimitiveType(node: PrimitiveType): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PrimitiveType")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorlist'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeObjectType(node: ObjectType): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("ObjectType")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    private checkDuplicateNamesInNamespace(node: FreNode) {
        const declaredNodes: Set<FreNamedNode> = FreNamespace.create(node).getDeclaredNodes(false);
        const declaredNames: string[] = [];
        const doubleNames: string[] = [];
        declaredNodes.forEach((nn) => {
            if (declaredNames.indexOf(nn.name) > -1) {
                doubleNames.push(nn.name);
            } else {
                declaredNames.push(nn.name);
            }
        });
        if (doubleNames.length > 0) {
            const namespaceName: string = "name" in node ? (node as FreNamedNode).name : "<unnamed>";
            this.errorList.push(
                new FreError(
                    `Namespace ${namespaceName} has multiple nodes with the same name [${doubleNames.map((n) => n).join(", ")}].`,
                    node,
                    namespaceName,
                    "name",
                    FreErrorSeverity.Error,
                ),
            );
        }
    }
}
