// Generated by the Freon Language Generator.
// Run this as the main program.
import { LionCore_M3Environment } from "../config/gen/LionCore_M3Environment";
import { ConvertLionCoreFolder2FreonAction } from "./ConvertLionCoreFolder2FreonAction";
import { FreonCommandLine } from "./FreonCommandLine";
import { DummyAction } from "./DummyAction";

// ensure language is initialized
const tmp = LionCore_M3Environment.getInstance();

// Create the command line object
const cli: FreonCommandLine = new FreonCommandLine();

// Add specific actions to the command line tool
// REPLACE WITH YOUR OWN
cli.addAction(new ConvertLionCoreFolder2FreonAction());

// Run it
cli.execute();
