// Generated by the Freon Language Generator.
// Run this as the main program.
import { LionCoreM3Environment } from "../config/gen/LionCoreM3Environment";
import { ConvertLionCoreFile2FreonAction } from "./ConvertLionCoreFile2FreonAction";
import { ConvertLionCoreFolder2FreonAction } from "./ConvertLionCoreFolder2FreonAction";
import { FreonCommandLine } from "./FreonCommandLine";
import { DummyAction } from "./DummyAction";

// ensure language is initialized
const tmp = LionCoreM3Environment.getInstance();

// Create the command line object
const cli: FreonCommandLine = new FreonCommandLine();

// Add specific actions to the command line tool
// REPLACE WITH YOUR OWN
cli.addAction(new ConvertLionCoreFile2FreonAction());
cli.addAction(new ConvertLionCoreFolder2FreonAction());

// Run it
cli.execute();
