// Generated by the Freon Language Generator.
import { type FreCompositeTyper } from "@freon4dsl/core";

import { ProtocolTyperPart } from "./ProtocolTyperPart.js";
import { freonConfiguration } from "../../custom/FreonConfiguration.js";

/**
 * Adds all known type-providers the root typer.
 * @param rootTyper
 */
export function initializeTypers(rootTyper: FreCompositeTyper) {
    for (const p of freonConfiguration.customTypers) {
        rootTyper.appendTyper(p);
    }
    rootTyper.appendTyper(new ProtocolTyperPart());
}
