// Generated by the Freon Language Generator.
// TEMPLATE: WorkerInterfaceTemplate.generateWorkerInterface(...)

import { PropertyDef, PrimitiveType, ObjectType, Types, MessageGroup, Protocol } from "../language/index.js";

/**
 * Interface ProtocolWorker implements the extended visitor pattern of instances of language Protocol.
 * Class ProtocolWalker implements the traversal of the model tree, classes that implement this interface
 * are responsible for the actual work being done on the nodes of the tree.
 * Every node is visited twice, once before the visit of its children, and once after this visit.
 */
export interface ProtocolWorker {
    execBeforeProtocol(node: Protocol): boolean;
    execAfterProtocol(node: Protocol): boolean;

    execBeforeTypes(node: Types): boolean;
    execAfterTypes(node: Types): boolean;

    execBeforeMessageGroup(node: MessageGroup): boolean;
    execAfterMessageGroup(node: MessageGroup): boolean;

    execBeforePropertyDef(node: PropertyDef): boolean;
    execAfterPropertyDef(node: PropertyDef): boolean;

    execBeforePrimitiveType(node: PrimitiveType): boolean;
    execAfterPrimitiveType(node: PrimitiveType): boolean;

    execBeforeObjectType(node: ObjectType): boolean;
    execAfterObjectType(node: ObjectType): boolean;
}
