// Generated by the Freon Language Generator.
// TEMPLATE: WalkerTemplate.generateWalker(...)

import { FreLogger, type FreNode, notNullOrUndefined } from "@freon4dsl/core";
import { ObjectType, PrimitiveType, PropertyDef, Types, MessageGroup, Protocol } from "../language/index.js";

import { type ProtocolWorker } from "./ProtocolWorker.js";

const LOGGER = new FreLogger("ProtocolWalker");

/**
 * Class ProtocolWalker implements the extended visitor pattern of instances of language Protocol.
 * This class implements the traversal of the model tree, classes that implement ProtocolWorker
 * are responsible for the actual work being done on the nodes of the tree.
 * Every node is visited twice, once before the visit of its children, and once after this visit.
 *
 * With the use of the parameter 'includeChildren', which takes a function, a very fine-grained control can be taken
 * over which nodes are and are not visited.
 */
export class ProtocolWalker {
    myWorkers: ProtocolWorker[] = []; // the instances that do the actual work on each node of the tree

    /**
     * This method is the entry point of the traversal through the model tree. Each of the workers will be called in
     * the order in which they are present in the array 'myWorkers'. If, for a tree node, a worker returns 'false',
     * none of the rest of the workers will be called. For that particular node both the 'execBefore' and 'execAfter'
     * method of any of the other workers will be skipped.
     *
     * @param node the top node of the part of the tree to be visited
     * @param includeChildren if true, the children of 'node' will also be visited
     */
    public walk(node: FreNode, includeChildren?: (elem: FreNode) => boolean) {
        if (this.myWorkers.length > 0) {
            if (node instanceof ObjectType) {
                return this.walkObjectType(node, includeChildren);
            }
            if (node instanceof PrimitiveType) {
                return this.walkPrimitiveType(node, includeChildren);
            }
            if (node instanceof PropertyDef) {
                return this.walkPropertyDef(node, includeChildren);
            }
            if (node instanceof Types) {
                return this.walkTypes(node, includeChildren);
            }
            if (node instanceof MessageGroup) {
                return this.walkMessageGroup(node, includeChildren);
            }
            if (node instanceof Protocol) {
                return this.walkProtocol(node, includeChildren);
            }
        } else {
            LOGGER.error("No worker found.");
        }
    }

    private walkObjectType(node: ObjectType, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeObjectType(node);
            }
        }
        // work on children in the model tree
        node.properties.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterObjectType(node);
            }
        }
    }

    private walkPrimitiveType(node: PrimitiveType, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePrimitiveType(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPrimitiveType(node);
            }
        }
    }

    private walkPropertyDef(node: PropertyDef, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePropertyDef(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPropertyDef(node);
            }
        }
    }

    private walkTypes(node: Types, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTypes(node);
            }
        }
        // work on children in the model tree
        node.primitiveTypes.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.objectTypes.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTypes(node);
            }
        }
    }

    private walkMessageGroup(node: MessageGroup, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeMessageGroup(node);
            }
        }
        // work on children in the model tree
        node.messages.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.sharedProperties.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterMessageGroup(node);
            }
        }
    }

    private walkProtocol(node: Protocol, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeProtocol(node);
            }
        }
        // work on children in the model tree
        node.categories.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.typeDefinitions.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterProtocol(node);
            }
        }
    }
}
