// Generated by the Freon Language Generator.
// TEMPLATE: DefaultWorkerTemplate.generateDefaultWorker(...)

import { PropertyDef, PrimitiveType, ObjectType, Types, MessageGroup, Protocol } from "../language/index.js";

import { type ProtocolWorker } from "./ProtocolWorker.js";

/**
 * Class ProtocolDefaultWorker is part of the implementation of the visitor pattern on models.
 * It implements the interface ProtocolWorker with empty methods, and can thus be used as
 * base to any class that needs to traverse the model tree.
 * Class ProtocolWalker implements the traversal of the model tree. This class implements
 * the actual visiting of each node in the tree.
 */
export class ProtocolDefaultWorker implements ProtocolWorker {
    /**
     * Visits 'node' before visiting its children.
     * @param node
     */
    public execBeforeProtocol(node: Protocol): boolean {
        return false;
    }

    /**
     * Visits 'node' after visiting its children.
     * @param node
     */
    public execAfterProtocol(node: Protocol): boolean {
        return false;
    }

    /**
     * Visits 'node' before visiting its children.
     * @param node
     */
    public execBeforeTypes(node: Types): boolean {
        return false;
    }

    /**
     * Visits 'node' after visiting its children.
     * @param node
     */
    public execAfterTypes(node: Types): boolean {
        return false;
    }

    /**
     * Visits 'node' before visiting its children.
     * @param node
     */
    public execBeforeMessageGroup(node: MessageGroup): boolean {
        return false;
    }

    /**
     * Visits 'node' after visiting its children.
     * @param node
     */
    public execAfterMessageGroup(node: MessageGroup): boolean {
        return false;
    }

    /**
     * Visits 'node' before visiting its children.
     * @param node
     */
    public execBeforePropertyDef(node: PropertyDef): boolean {
        return false;
    }

    /**
     * Visits 'node' after visiting its children.
     * @param node
     */
    public execAfterPropertyDef(node: PropertyDef): boolean {
        return false;
    }

    /**
     * Visits 'node' before visiting its children.
     * @param node
     */
    public execBeforePrimitiveType(node: PrimitiveType): boolean {
        return false;
    }

    /**
     * Visits 'node' after visiting its children.
     * @param node
     */
    public execAfterPrimitiveType(node: PrimitiveType): boolean {
        return false;
    }

    /**
     * Visits 'node' before visiting its children.
     * @param node
     */
    public execBeforeObjectType(node: ObjectType): boolean {
        return false;
    }

    /**
     * Visits 'node' after visiting its children.
     * @param node
     */
    public execAfterObjectType(node: ObjectType): boolean {
        return false;
    }
}
