// Generated by the Freon Language Generator.
// TEMPLATE: ScoperDefTemplate.generateScoperDef(...)

import { FreLanguage, FreCompositeScoper } from "@freon4dsl/core";

import { freonConfiguration } from "../../custom/FreonConfiguration.js";
import { ProtocolScoper } from "./ProtocolScoper.js";

/**
 * Adds all known scopers to the main scoper.
 * @param rootScoper
 */
export function initializeScopers(rootScoper: FreCompositeScoper) {
    for (const p of freonConfiguration.customScopers) {
        rootScoper.appendScoper(p);
    }
    rootScoper.appendScoper(new ProtocolScoper());
}

/**
 * Adds namespace info to the in-memory representation of the language metamodel.
 */
export function initializeScoperDef(rootScoper: FreCompositeScoper) {
    FreLanguage.getInstance().classifier("Types")!.isNamespace = true;
    FreLanguage.getInstance().classifier("MessageGroup")!.isNamespace = true;
    FreLanguage.getInstance().classifier("ObjectType")!.isNamespace = true;
    initializeScopers(rootScoper);
}
