// Generated by the Freon Language Generator.
import { FreScoperBase, type FreNode, FreNamespaceInfo, FreLanguage, isNullOrUndefined, notNullOrUndefined } from "@freon4dsl/core";
import { ObjectType, MessageGroup, Protocol, Types } from "../language/index.js";

/**
 * Class ProtocolScoper implements the scoper generated from, if present, the scoper definition,
 * otherwise this class implements the default scoper.
 */
export class ProtocolScoper extends FreScoperBase {
    /**
     * Returns all FreNodes or FreNodeReferences that are defined as alternative namespaces for 'node'.
     * @param node
     */
    public alternativeNamespaces(node: FreNode): FreNamespaceInfo[] {
        const result: FreNamespaceInfo[] = [];
        // namespace replacement for ObjectType
        if (node instanceof ObjectType) {
            // generated from 'self.owner().if(MessageGroup).owner().typeDefinitions;'
            const list0 = (
                (FreLanguage.getInstance().metaConformsToType(node.freOwner(), "MessageGroup")
                    ? (node.freOwner() as MessageGroup)
                    : undefined
                )?.freOwner() as Protocol
            )?.typeDefinitions;
            if (notNullOrUndefined(list0)) {
                for (let loopVariable of list0) {
                    if (!isNullOrUndefined(loopVariable)) {
                        result.push(new FreNamespaceInfo(loopVariable, false));
                    }
                }
            }
            // generated from 'self.owner().if(MessageGroup).owner();'
            const xx1: Protocol | undefined = (
                FreLanguage.getInstance().metaConformsToType(node.freOwner(), "MessageGroup")
                    ? (node.freOwner() as MessageGroup)
                    : undefined
            )?.freOwner() as Protocol;
            if (!isNullOrUndefined(xx1)) {
                result.push(new FreNamespaceInfo(xx1, false));
            }
            // generated from 'self.owner().if(Types).owner().typeDefinitions;'
            const list2 = (
                (FreLanguage.getInstance().metaConformsToType(node.freOwner(), "Types")
                    ? (node.freOwner() as Types)
                    : undefined
                )?.freOwner() as Protocol
            )?.typeDefinitions;
            if (notNullOrUndefined(list2)) {
                for (let loopVariable of list2) {
                    if (!isNullOrUndefined(loopVariable)) {
                        result.push(new FreNamespaceInfo(loopVariable, false));
                    }
                }
            }
            // generated from 'self.owner().if(Types).owner();'
            const xx3: Protocol | undefined = (
                FreLanguage.getInstance().metaConformsToType(node.freOwner(), "Types") ? (node.freOwner() as Types) : undefined
            )?.freOwner() as Protocol;
            if (!isNullOrUndefined(xx3)) {
                result.push(new FreNamespaceInfo(xx3, false));
            }
        }

        return result;
    }

    /**
     * Returns all FreNodes or FreNodeReferences that are defined as imported namespaces for 'node'.
     * @param node
     */
    public importedNamespaces(node: FreNode): FreNamespaceInfo[] {
        const result: FreNamespaceInfo[] = [];
        // namespace addition for MessageGroup
        if (node instanceof MessageGroup) {
            // generated from 'self.owner().typeDefinitions;'
            const list0 = (node.freOwner() as Protocol).typeDefinitions;
            if (notNullOrUndefined(list0)) {
                for (let loopVariable of list0) {
                    if (!isNullOrUndefined(loopVariable)) {
                        result.push(new FreNamespaceInfo(loopVariable, false));
                    }
                }
            }
        }
        // namespace addition for Types
        if (node instanceof Types) {
            // generated from 'self.owner().typeDefinitions;'
            const list0 = (node.freOwner() as Protocol).typeDefinitions;
            if (notNullOrUndefined(list0)) {
                for (let loopVariable of list0) {
                    if (!isNullOrUndefined(loopVariable)) {
                        result.push(new FreNamespaceInfo(loopVariable, false));
                    }
                }
            }
        }

        return result;
    }
}
