// Generated by the Freon Language Generator.
// TEMPLATE: CustomProjectionTemplate.generate(...)

import { type FreNode, Box, type FreProjection, type FreTableDefinition, FreProjectionHandler } from "@freon4dsl/core";

/**
 * Class CustomModel2Projection provides an entry point for the language engineer to
 * define custom build additions to the editor.
 * These are merged with the custom build additions and other definition-based editor parts
 * in a three-way manner. For each node,
 * (1) if a custom build creator/behavior is present, this is used,
 * (2) if a creator/behavior based on one of the editor definition is present, this is used,
 * (3) if neither (1) nor (2) yields a result, the default is used.
 */
export class CustomModel2Projection implements FreProjection {
    name: string = "Custom";
    handler!: FreProjectionHandler; // will get a value in Environment
    nodeTypeToBoxMethod: Map<string, (node: FreNode) => Box> = new Map<string, (node: FreNode) => Box>([
        // register your custom box methods here
        // ['NAME_OF_CONCEPT', this.BOX_FOR_CONCEPT],
    ]);
    nodeTypeToTableDefinition: Map<string, () => FreTableDefinition> = new Map<string, () => FreTableDefinition>([
        // register your custom table definition methods here
        // ['NAME_OF_CONCEPT', this.TABLE_DEFINITION_FOR_CONCEPT],
    ]);

    // add your custom methods here

    // BOX_FOR_CONCEPT(node: FreNode): Box { ... }
    // Note: The map type is (node: FreNode) => Box, which means handlers
    // must accept *any* FreNode. A method with signature (node: NAME_OF_CONCEPT): Box
    // is not assignable, even though EuroLiteral extends FreNode, because
    // function parameters are checked contravariantly in TypeScript.
    // => Fix: declare the handler as (node: FreNode) and cast/narrow inside.

    // TABLE_DEFINITION_FOR_CONCEPT() : FreTableDefinition { ... }
}
