// Generated by the Freon Language Generator.
// TEMPLATE EnvironmentTemplate.generateEnvironment(...)

import {
    FreEditor,
    type FreEnvironment,
    type FreReader,
    FreCompositeTyper,
    type FreValidator,
    type FreStdlib,
    type FreWriter,
    type FreInterpreter,
    FreCompositeScoper,
    FreLanguageEnvironment,
    FreProjectionHandler,
} from "@freon4dsl/core";
import { Protocol, Types, initializeLanguage } from "../language/index.js";

import { ProtocolActions, initializeEditorDef, initializeProjections } from "../editor/index.js";

import { initializeScoperDef } from "../scoper/index.js";
import { initializeTypers } from "../typer/index.js";
import { ProtocolValidator } from "../validator/index.js";
import { ProtocolStdlib } from "../stdlib/ProtocolStdlib.js";
import { ProtocolModelUnitWriter } from "../writer/ProtocolModelUnitWriter.js";
import { ProtocolModelUnitReader } from "../reader/ProtocolModelUnitReader.js";
import { MainProtocolInterpreter } from "../../custom/MainProtocolInterpreter.js";

/**
 * Class ProtocolEnvironment provides the link between all parts of the language environment.
 * It holds the currently used editor, scoper, typer, etc, thus providing an entry point for,
 * for instance, the editor to find the right scoper, or for the validator to find the typer
 * to use.
 * This class uses the singleton pattern to ensure that only one instance of the class is present.
 */
export class ProtocolEnvironment implements FreEnvironment {
    private static environment: FreEnvironment; // the only instance of this class

    /**
     * This method implements the singleton pattern
     */
    public static getInstance(): FreEnvironment {
        if (this.environment === undefined || this.environment === null) {
            this.environment = new ProtocolEnvironment();
            FreLanguageEnvironment.setInstance(this.environment);
        }
        return this.environment;
    }

    /**
     * A private constructor, as demanded by the singleton pattern.
     */
    private constructor() {
        const actions = new ProtocolActions();
        const myComposite = new FreProjectionHandler();
        this.editor = new FreEditor(myComposite, this, actions);
        initializeLanguage();
        initializeProjections(myComposite);
        initializeEditorDef();
        initializeScoperDef(this.scoper);
        initializeTypers(this.typer);
        this.projectionHandler = myComposite;
    }

    /**
     * Returns a new model with name 'modelName'.
     *
     * @param modelName
     */
    newModel(modelName: string): Protocol {
        const model = new Protocol();
        model.name = modelName;
        return model;
    }

    // the parts of the language environment
    editor: FreEditor;
    scoper: FreCompositeScoper = new FreCompositeScoper();
    typer: FreCompositeTyper = new FreCompositeTyper("main");
    validator: FreValidator = new ProtocolValidator();
    writer: FreWriter = new ProtocolModelUnitWriter();
    reader: FreReader = new ProtocolModelUnitReader();
    interpreter: FreInterpreter = new MainProtocolInterpreter();
    stdlib: FreStdlib = ProtocolStdlib.getInstance();
    projectionHandler: FreProjectionHandler;
    languageName: string = "Protocol";
    fileExtensions: Map<string, string> = new Map([
        ["MessageGroup", "mes"],
        ["Types", "typ"],
    ]);
}
