// Generated by the Freon Language Generator.
import { CoreConfig } from "@freon4dsl/core";
// Run this as the main program.
import { LionCore_M3Environment } from "../freon/config/LionCore_M3Environment.js";
import { ConvertLionCoreFolder2FreonAction } from "./ConvertLionCoreFolder2FreonAction.js";
import { FreonCommandLine } from "../freon/commandline/FreonCommandLine.js";

// ensure language is initialized
const tmp = LionCore_M3Environment.getInstance();

// Create the command line object
const cli: FreonCommandLine = new FreonCommandLine();
CoreConfig.initialize(tmp, null)

// Add specific actions to the command line tool
cli.addAction(new ConvertLionCoreFolder2FreonAction());

// Run it
await cli.executeAsync();
