// Generated by the Freon Language Generator.
// TEMPLATE: ConfigurationTemplate.generate(...)

import { type FreProjection, type FreCombinedActions, type FreTyper, type FreStdlib, type FreScoper } from "@freon4dsl/core";

import { CustomLionCore_M3Actions } from "./CustomLionCore_M3Actions.js";
import { CustomLionCore_M3Projection } from "./CustomLionCore_M3Projection.js";
import { CustomLionCore_M3Scoper } from "./CustomLionCore_M3Scoper.js";
import { CustomLionCore_M3TyperPart } from "./CustomLionCore_M3TyperPart.js";
import { CustomLionCore_M3Validator } from "./CustomLionCore_M3Validator.js";
import { CustomLionCore_M3Stdlib } from "./CustomLionCore_M3Stdlib.js";
import { type LionCore_M3CheckerInterface } from "../freon/validator/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customizations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomLionCore_M3Projection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomLionCore_M3Actions()];
    // add your custom validations here
    customValidations: LionCore_M3CheckerInterface[] = [new CustomLionCore_M3Validator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomLionCore_M3Scoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomLionCore_M3TyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomLionCore_M3Stdlib()];
}

export const freonConfiguration = new FreonConfiguration();
