// Generated by the Freon Language Generator.
// TEMPLATE: ConfigurationTemplate.generate(...)

import { type FreProjection, type FreCombinedActions, type FreTyper, type FreStdlib, type FreScoper } from "@freon4dsl/core";

import { CustomModel2Actions, CustomModel2Projection } from "../editor/index.js";
import { CustomModel2Scoper } from "../scoper/index.js";
import { CustomModel2TyperPart } from "../typer/CustomModel2TyperPart.js";
import { CustomModel2Validator } from "../validator/index.js";
import { CustomModel2Stdlib } from "../stdlib/CustomModel2Stdlib.js";
import { type Model2CheckerInterface } from "../validator/gen/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customizations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomModel2Projection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomModel2Actions()];
    // add your custom validations here
    customValidations: Model2CheckerInterface[] = [new CustomModel2Validator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomModel2Scoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomModel2TyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomModel2Stdlib()];
}

export const freonConfiguration = new FreonConfiguration();
