// Generated by the Freon Language Generator.
import { FreProjection, FreCombinedActions, FreTyper, FreStdlib, FreScoper } from "@freon4dsl/core";
import { CustomLionCore_M3Actions, CustomLionCore_M3Projection } from "../editor/index.js";
import { CustomLionCore_M3Scoper } from "../scoper/index.js";
import { CustomLionCore_M3TyperPart } from "../typer/CustomLionCore_M3TyperPart.js";
import { CustomLionCore_M3Validator } from "../validator/index.js";
import { CustomLionCore_M3Stdlib } from "../stdlib/CustomLionCore_M3Stdlib.js";
import { LionCore_M3CheckerInterface } from "../validator/gen/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomLionCore_M3Projection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomLionCore_M3Actions()];
    // add your custom validations here
    customValidations: LionCore_M3CheckerInterface[] = [new CustomLionCore_M3Validator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomLionCore_M3Scoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomLionCore_M3TyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomLionCore_M3Stdlib()];
}

export const freonConfiguration = new FreonConfiguration();
