// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { Model2DefaultWorker } from "../utils/gen/index.js";
import { type Model2CheckerInterface } from "./gen/Model2Validator.js";

export class CustomModel2Validator extends Model2DefaultWorker implements Model2CheckerInterface {
    errorList: FreError[] = [];
}
