// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { LogoDefaultWorker } from "../utils/gen/index.js";
import { type LogoCheckerInterface } from "./gen/LogoValidator.js";

export class CustomLogoValidator extends LogoDefaultWorker implements LogoCheckerInterface {
    errorList: FreError[] = [];
}
