// Generated by the Freon Language Generator.
// TEMPLATE: CommandLineTemplate.generateCommandLine()
import { CommandLineFlagParameter, CommandLineParser } from "@rushstack/ts-command-line";

export class FreonCommandLine extends CommandLineParser {
    private verboseArg!: CommandLineFlagParameter;

    public constructor() {
        super({
            toolFilename: "lionweb",
            toolDescription: "Freon toolset for playing with LionWeb.",
        });

        this.verboseArg = this.defineFlagParameter({
            parameterLongName: "--verbose",
            parameterShortName: "-v",
            description: "Show extra logging detail",
        });
    }

    protected async onExecuteAsync(): Promise<void> {
        try {
            await super.onExecuteAsync();
        } catch (e: unknown) {
            const err = e instanceof Error ? e : new Error(String(e));
            console.error(`Exception in onExecuteAsync: ${err.message}\n${err.stack ?? ""}`);
            throw err;
        }
    }
}
