// Generated by the Freon Language Generator.
// TEMPLATE: EditorDefTemplate.generateEditorDef(...)

import { FreLanguage, FreProjectionHandler, FreBoxProvider, type FreLanguageConcept } from "@freon4dsl/core";
import { PropertyDef, PrimitiveType, ObjectType } from "../language/index.js";

import {
    PropertyDefBoxProvider,
    PrimitiveTypeBoxProvider,
    ObjectTypeBoxProvider,
    TypesBoxProvider,
    MessageGroupBoxProvider,
} from "../editor/index.js";

import { freonConfiguration } from "../../custom/FreonConfiguration.js";

const map = new Map([
    // the main map
    [
        // Concept has special projection for (one of) its parts
        "PropertyDef",
        new Map([
            // Projection has special projection for (one of) the parts
            [
                // Projection has special projection for some part
                "default",
                new Map([
                    ["name", ""], // special projection
                    ["type", ""], // special projection
                    ["mayBeNull", ""], // special projection
                    ["isList", ""], // special projection
                    ["isOptional", ""], // special projection
                ]),
            ],
        ]),
    ],
    [
        // Concept has special projection for (one of) its parts
        "PrimitiveType",
        new Map([
            // Projection has special projection for (one of) the parts
            [
                // Projection has special projection for some part
                "default",
                new Map([
                    ["name", ""], // special projection
                    ["primitiveType", ""], // special projection
                ]),
            ],
        ]),
    ],
    [
        // Concept has special projection for (one of) its parts
        "ObjectType",
        new Map([
            // Projection has special projection for (one of) the parts
            [
                // Projection has special projection for some part
                "default",
                new Map([
                    ["name", ""], // special projection
                    ["properties", ""], // special projection
                ]),
            ],
        ]),
    ],
    [
        // Concept has special projection for (one of) its parts
        "Types",
        new Map([
            // Projection has special projection for (one of) the parts
            [
                // Projection has special projection for some part
                "default",
                new Map([
                    ["name", ""], // special projection
                    ["primitiveTypes", ""], // special projection
                    ["objectTypes", ""], // special projection
                ]),
            ],
        ]),
    ],
    [
        // Concept has special projection for (one of) its parts
        "MessageGroup",
        new Map([
            // Projection has special projection for (one of) the parts
            [
                // Projection has special projection for some part
                "default",
                new Map([
                    ["name", ""], // special projection
                    ["taggedUnionProperty", ""], // special projection
                    ["sharedProperties", ""], // special projection
                    ["messages", ""], // special projection
                ]),
            ],
        ]),
    ],
]);

/**
 * Adds all known projection groups to the root projection.
 * @param handler
 */
export function initializeProjections(handler: FreProjectionHandler) {
    for (const p of freonConfiguration.customProjection) {
        handler.addCustomProjection(p);
    }
    handler.initConceptToPropertyProjection(map);
    handler.initProviderConstructors(
        new Map<string, () => FreBoxProvider>([
            [
                "PropertyDef",
                () => {
                    return new PropertyDefBoxProvider(handler);
                },
            ],
            [
                "PrimitiveType",
                () => {
                    return new PrimitiveTypeBoxProvider(handler);
                },
            ],
            [
                "ObjectType",
                () => {
                    return new ObjectTypeBoxProvider(handler);
                },
            ],
            [
                "Types",
                () => {
                    return new TypesBoxProvider(handler);
                },
            ],
            [
                "MessageGroup",
                () => {
                    return new MessageGroupBoxProvider(handler);
                },
            ],
        ]),
    );
    handler.initTableHeaders([]);
}

/**
 * Helper function to ensure that the meta information for typeName can be found.
 * @param typeName
 */
export function conceptRequired(typeName: string): FreLanguageConcept {
    const c = FreLanguage.getInstance().concept(typeName);
    if (!c) {
        throw new Error(`Concept '${typeName}' not found in language.`);
    }
    return c;
}

/**
 * Adds trigger and reference shortcut info to the in-memory representation of structure of the language metamodel.
 */
export function initializeEditorDef() {
    conceptRequired("PropertyDef").trigger = "PropertyDef";
    conceptRequired("PrimitiveType").trigger = "PrimitiveType";
    conceptRequired("ObjectType").trigger = "ObjectType";

    const conceptProjectionToPropertyProjection = new Map();
}
