// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, BoxFactory, FreListInfo } from "@freon4dsl/core";
import { ObjectType } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type ObjectType.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class ObjectTypeBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default"];
        this.knownTableProjections = ["default"];
        this.conceptName = "ObjectType";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxFactory.verticalLayout(
            this._node as ObjectType,
            "ObjectType-overall",
            "",
            [
                BoxFactory.horizontalLayout(
                    this._node as ObjectType,
                    "ObjectType-hlist-line-0",
                    "",
                    [
                        BoxUtil.labelBox(this._node as ObjectType, "object", "top-1-line-0-item-0"),
                        BoxUtil.textBox(this._node as ObjectType, "name"),
                    ],
                    { selectable: false },
                ),
                BoxUtil.indentBox(
                    this._node as ObjectType,
                    4,
                    "1",
                    BoxUtil.verticalPartListBox(
                        this._node as ObjectType,
                        (this._node as ObjectType).properties,
                        "properties",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                ),
                BoxUtil.emptyLineBox(this._node as ObjectType, "ObjectType-empty-line-2"),
            ],
            { cssClass: "ObjectType" },
        );
    }
}
