// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import {
    Box,
    BoxUtil,
    FreBoxProvider,
    FreProjectionHandler,
    BoolDisplay,
    BoxFactory,
    FragmentBox,
    FreNodeReference,
    type FreNamedNode,
} from "@freon4dsl/core";
import { PropertyDef, type Type } from "../language/index.js";

import { LanguageEnvironment } from "../index.js";

/**
 * This class implements the box provider for a single node of type PropertyDef.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class PropertyDefBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default"];
        this.knownTableProjections = ["default"];
        this.conceptName = "PropertyDef";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxFactory.horizontalLayout(
            this._node as PropertyDef,
            "PropertyDef-hlist-line-0",
            "",
            [
                this.getFragmentBox_Options(),
                BoxUtil.textBox(this._node as PropertyDef, "name"),
                BoxUtil.labelBox(this._node as PropertyDef, ":", "top-1-line-0-item-2"),
                BoxUtil.referenceBox(
                    this._node as PropertyDef,
                    "type",
                    (selected: string | FreNamedNode) => {
                        const ref =
                            typeof selected === "string"
                                ? FreNodeReference.create<Type>(selected, "Type")
                                : FreNodeReference.create<Type>(selected as Type, "Type");
                        (this._node as PropertyDef).type = ref;
                    },
                    LanguageEnvironment.getInstance().scoper,
                ),
            ],
            { selectable: false },
        );
    }

    private getFragmentBox_Options(): FragmentBox {
        return new FragmentBox(
            this._node as PropertyDef,
            "PropertyDef-fragment-Options",
            BoxFactory.horizontalLayout(
                this._node as PropertyDef,
                "PropertyDef-fragment-Options-hlist-line-0",
                "",
                [
                    BoxUtil.booleanBox(
                        this._node as PropertyDef,
                        "mayBeNull",
                        { yes: "true", no: "false", unknown: "unknown" },
                        BoolDisplay.CHECKBOX,
                    ),
                    BoxUtil.labelBox(this._node as PropertyDef, "may be null", "top-1-line-0-item-1"),
                    BoxUtil.booleanBox(
                        this._node as PropertyDef,
                        "isList",
                        { yes: "true", no: "false", unknown: "unknown" },
                        BoolDisplay.CHECKBOX,
                    ),
                    BoxUtil.labelBox(this._node as PropertyDef, "is a list", "top-1-line-0-item-3"),
                    BoxUtil.booleanBox(
                        this._node as PropertyDef,
                        "isOptional",
                        { yes: "true", no: "false", unknown: "unknown" },
                        BoolDisplay.CHECKBOX,
                    ),
                    BoxUtil.labelBox(this._node as PropertyDef, "optional", "top-1-line-0-item-5"),
                ],
                { selectable: false },
            ),
            { cssClass: "PropertyDef-fragment-Options" },
        );
    }
}
