/**
  * Defines constants for all metapointers in the "Protocol" language.
  * Generated by Freon LionWeb M3 generator
  */
const Node = {"language":"LionCore-builtins","key":"LionCore-builtins-Node","version":"1"}
const INamed = {"language":"LionCore-builtins","key":"LionCore-builtins-INamed","version":"1"}
const MessageGroup = {"language":"-key-Protocol","key":"-key-MessageGroup","version":"1"}
const PropertyDef = {"language":"-key-Protocol","key":"-key-PropertyDef","version":"1"}
const PrimitiveType = {"language":"-key-Protocol","key":"-key-PrimitiveType","version":"1"}
const ObjectType = {"language":"-key-Protocol","key":"-key-ObjectType","version":"1"}
const Type = {"language":"-key-Protocol","key":"-key-Type","version":"1"}
const Types = {"language":"-key-Protocol","key":"-key-Types","version":"1"}

export const CLASSIFIER = {
            Node,INamed,MessageGroup,PropertyDef,PrimitiveType,ObjectType,Type,Types 
        }
const INamedName = {"language":"LionCore-builtins","key":"LionCore-builtins-INamed-name","version":"2023.1"}
const MessageGroupTaggedUnionProperty = {"language":"-key-Protocol","key":"-key-MessageGroup-taggedUnionProperty","version":"1"}
const PropertyDefName = {"language":"-key-Protocol","key":"-key-PropertyDef-name","version":"1"}
const PropertyDefMayBeNull = {"language":"-key-Protocol","key":"-key-PropertyDef-mayBeNull","version":"1"}
const PropertyDefIsList = {"language":"-key-Protocol","key":"-key-PropertyDef-isList","version":"1"}
const PropertyDefIsOptional = {"language":"-key-Protocol","key":"-key-PropertyDef-isOptional","version":"1"}
const PrimitiveTypePrimitiveType = {"language":"-key-Protocol","key":"-key-PrimitiveType-primitiveType","version":"1"}
const PrimitiveTypeValidator = {"language":"-key-Protocol","key":"-key-PrimitiveType-validator","version":"1"}
const TypeName = {"language":"-key-Protocol","key":"-key-Type-name","version":"2023.1"}
const TypesName = {"language":"-key-Protocol","key":"-key-Types-name","version":"1"}

export const PROPERTY = {
            INamedName,MessageGroupTaggedUnionProperty,PropertyDefName,PropertyDefMayBeNull,PropertyDefIsList,PropertyDefIsOptional,PrimitiveTypePrimitiveType,PrimitiveTypeValidator,TypeName,TypesName 
        }
const PropertyDefType = {"language":"-key-Protocol","key":"-key-PropertyDef-type","version":"1"}

export const REFERENCE = {
            PropertyDefType 
        }
const MessageGroupSharedProperties = {"language":"-key-Protocol","key":"-key-MessageGroup-sharedProperties","version":"1"}
const MessageGroupMessages = {"language":"-key-Protocol","key":"-key-MessageGroup-messages","version":"1"}
const ObjectTypeProperties = {"language":"-key-Protocol","key":"-key-ObjectType-properties","version":"1"}
const TypesPrimitiveTypes = {"language":"-key-Protocol","key":"-key-Types-primitiveTypes","version":"1"}
const TypesObjectTypes = {"language":"-key-Protocol","key":"-key-Types-objectTypes","version":"1"}

export const CONTAINMENT = {
            MessageGroupSharedProperties,MessageGroupMessages,ObjectTypeProperties,TypesPrimitiveTypes,TypesObjectTypes 
        }
