// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { LionCore_M3DefaultWorker } from "../utils/gen/index.js";
import { type LionCore_M3CheckerInterface } from "./gen/LionCore_M3Validator.js";

export class CustomLionCore_M3Validator extends LionCore_M3DefaultWorker implements LionCore_M3CheckerInterface {
    errorList: FreError[] = [];
}
