// Generated by the Freon Language Generator.
import { errorLocation, type FreNode } from "@freon4dsl/core";

/**
 * The function locationDescription turns the information on the location of a node
 * within the model into a human-readable string. It is used for error messages.
 *
 * @param node the node of which the location is described
 */
export function locationDescription(node: FreNode): string {
    let result: string = "";
    const loc: string[] = errorLocation(node);
    loc.reverse();
    for (let index = 0; index < loc.length; index++) {
        result += loc[index];
        if (index !== loc.length - 1) {
            result += " of ";
        }
    }
    return result;
}
