// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { ProtocolDefaultWorker } from "../freon/utils/index.js";
import { type ProtocolCheckerInterface } from "../freon/validator/ProtocolValidator.js";

export class CustomProtocolValidator extends ProtocolDefaultWorker implements ProtocolCheckerInterface {
    errorList: FreError[] = [];
}
