// Generated by the Freon Language Generator.
// TEMPLATE: ConfigurationTemplate.generate(...)

import { type FreProjection, type FreCombinedActions, type FreTyper, type FreStdlib, type FreScoper } from "@freon4dsl/core";

import { CustomProtocolActions } from "./CustomProtocolActions.js";
import { CustomProtocolProjection } from "./CustomProtocolProjection.js";
import { CustomProtocolScoper } from "./CustomProtocolScoper.js";
import { CustomProtocolTyperPart } from "./CustomProtocolTyperPart.js";
import { CustomProtocolValidator } from "./CustomProtocolValidator.js";
import { CustomProtocolStdlib } from "./CustomProtocolStdlib.js";
import { type ProtocolCheckerInterface } from "../freon/validator/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customizations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomProtocolProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomProtocolActions()];
    // add your custom validations here
    customValidations: ProtocolCheckerInterface[] = [new CustomProtocolValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomProtocolScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomProtocolTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomProtocolStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
