// Generated by the Freon Language Generator.
// TEMPLATE: InterpreterBaseTemplate.interpreterInit(...)
import { type IMainInterpreter } from "@freon4dsl/core";
import { ProtocolInterpreter } from "../../custom/ProtocolInterpreter.js";

/**
 * The class that registers all interpreter function with the main interpreter.
 */
export function ProtocolInterpreterInit(main: IMainInterpreter) {
    const interpreter = new ProtocolInterpreter(main);

    main.registerFunction("PropertyDef", interpreter.evalPropertyDef);
    main.registerFunction("PrimitiveType", interpreter.evalPrimitiveType);
    main.registerFunction("ObjectType", interpreter.evalObjectType);
    main.registerFunction("Types", interpreter.evalTypes);
    main.registerFunction("MessageGroup", interpreter.evalMessageGroup); // DONE
}
