// Generated by the Freon Language Generator.
// TEMPLATE: InterpreterBaseTemplate.interpreterBase(...)
// Will be overwritten with every generation.

import { InterpreterContext, RtObject, RtError } from "@freon4dsl/core";
import { PropertyDef, PrimitiveType, ObjectType, Types, MessageGroup } from "../language/index.js";

/**
 * The base class containing all interpreter functions that should be defined.
 * All functions throw an error when called.
 */
export class ProtocolInterpreterBase {
    constructor() {}

    evalPropertyDef(node: PropertyDef, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPropertyDef is not defined");
    }

    evalPrimitiveType(node: PrimitiveType, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPrimitiveType is not defined");
    }

    evalObjectType(node: ObjectType, ctx: InterpreterContext): RtObject {
        throw new RtError("evalObjectType is not defined");
    }

    evalTypes(node: Types, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTypes is not defined");
    }

    evalMessageGroup(node: MessageGroup, ctx: InterpreterContext): RtObject {
        throw new RtError("evalMessageGroup is not defined");
    }
}
