// Generated by the Freon Language Generator.
import { type KtList, type Sentence, type SpptDataNodeInfo } from "net.akehurst.language-agl-processor";
import { FreNodeReference, notNullOrUndefined } from "@freon4dsl/core";
import { MessageGroup, PropertyDef, ObjectType } from "../language/index.js";
import { PrimValueType, ProtocolSyntaxAnalyser } from "./ProtocolSyntaxAnalyser.js";

export class MessageGroupSyntaxAnalyserPart {
    mainAnalyser: ProtocolSyntaxAnalyser;

    constructor(mainAnalyser: ProtocolSyntaxAnalyser) {
        this.mainAnalyser = mainAnalyser;
    }

    /**
     * Method to transform branches that match the following rule:
     * MessageGroup = 'MessageGroup' identifier
     *	 'TaggedUnion' 'property' 'name' stringLiteral
     *	 'Shared' 'properties:'
     *	 PropertyDef*
     *	 'Messages'
     *	 ObjectType* ;
     * @param nodeInfo
     * @param children
     * @param sentence
     */
    public transformMessageGroup(nodeInfo: SpptDataNodeInfo, children: KtList<any>, sentence: Sentence): MessageGroup {
        // console.log('4 transformMessageGroup called: ' + children.toString());
        let __name: string;
        let __taggedUnionProperty: string;
        let __sharedProperties: PropertyDef[];
        let __messages: ObjectType[];
        __name = this.mainAnalyser.transformPrimValue<string>(
            children.asJsReadonlyArrayView()[1] as unknown as string,
            PrimValueType.identifier,
        ); // RHSPrimEntry
        __taggedUnionProperty = this.mainAnalyser.transformPrimValue<string>(
            children.asJsReadonlyArrayView()[5] as unknown as string,
            PrimValueType.string,
        ); // RHSPrimEntry
        __sharedProperties = (children.asJsReadonlyArrayView()[8] as KtList<any>).asJsReadonlyArrayView() as PropertyDef[]; // RHSPartListEntry
        __messages = (children.asJsReadonlyArrayView()[10] as KtList<any>).asJsReadonlyArrayView() as ObjectType[]; // RHSPartListEntry

        return MessageGroup.create({
            name: __name!,
            taggedUnionProperty: __taggedUnionProperty!,
            sharedProperties: __sharedProperties!,
            messages: __messages!,
            parseLocation: this.mainAnalyser.location(sentence, nodeInfo.node),
        });
    }
}
