// Generated by the Freon Language Generator.
import { type KtList, type Sentence, type SpptDataNodeInfo } from "net.akehurst.language-agl-processor";
import { FreNodeReference, notNullOrUndefined } from "@freon4dsl/core";
import { ObjectType, PropertyDef, Type } from "../language/index.js";
import { PrimValueType, ProtocolSyntaxAnalyser, ParsedNodeReference } from "./ProtocolSyntaxAnalyser.js";

export class ProtocolCommonSyntaxAnalyserPart {
    mainAnalyser: ProtocolSyntaxAnalyser;

    constructor(mainAnalyser: ProtocolSyntaxAnalyser) {
        this.mainAnalyser = mainAnalyser;
    }

    /**
     * Method to transform branches that match the following rule:
     * ObjectType = 'object' identifier
     *	 PropertyDef* ;
     * @param nodeInfo
     * @param children
     * @param sentence
     */
    public transformObjectType(nodeInfo: SpptDataNodeInfo, children: KtList<any>, sentence: Sentence): ObjectType {
        // console.log('4 transformObjectType called: ' + children.toString());
        let __name: string;
        let __properties: PropertyDef[];
        __name = this.mainAnalyser.transformPrimValue<string>(
            children.asJsReadonlyArrayView()[1] as unknown as string,
            PrimValueType.identifier,
        ); // RHSPrimEntry
        __properties = (children.asJsReadonlyArrayView()[2] as KtList<any>).asJsReadonlyArrayView() as PropertyDef[]; // RHSPartListEntry

        return ObjectType.create({
            name: __name!,
            properties: __properties!,
            parseLocation: this.mainAnalyser.location(sentence, nodeInfo.node),
        });
    }

    /**
     * Method to transform branches that match the following rule:
     * PropertyDef = identifier ':' __fre_reference ;
     * @param nodeInfo
     * @param children
     * @param sentence
     */
    public transformPropertyDef(nodeInfo: SpptDataNodeInfo, children: KtList<any>, sentence: Sentence): PropertyDef {
        // console.log('4 transformPropertyDef called: ' + children.toString());
        let __name: string;
        let __type: FreNodeReference<Type>;
        __name = this.mainAnalyser.transformPrimValue<string>(
            children.asJsReadonlyArrayView()[0] as unknown as string,
            PrimValueType.identifier,
        ); // RHSPrimEntry
        __type = this.mainAnalyser.makeFreNodeRef<Type>(children.asJsReadonlyArrayView()[2] as ParsedNodeReference, "Type"); // RHSRefEntry

        return PropertyDef.create({
            name: __name!,
            type: __type!,
            parseLocation: this.mainAnalyser.location(sentence, nodeInfo.node),
        });
    }
}
