// Generated by the Freon Language Generator.
// This file contains the input to the AGL parser generator
// (see https://https://github.com/dhakehurst/net.akehurst.language).
// The grammar in this file is read by ProtocolModelUnitReader

export const ProtocolGrammarStr = `
namespace ProtocolLanguage
grammar ProtocolGrammar {

// rules for "Types"
Types = 'Type' 'Definitions' identifier
	 'Primitives:'
	 PrimitiveType*
	 'Objects:'
	 ObjectType* ;

PrimitiveType = 'primitive' identifier ':' stringLiteral ;

// rules for "MessageGroup"
MessageGroup = 'MessageGroup' identifier
	 'TaggedUnion' 'property' 'name' stringLiteral
	 'Shared' 'properties:'
	 PropertyDef*
	 'Messages'
	 ObjectType* ;

// common rules
ObjectType = 'object' identifier
	 PropertyDef* ;

PropertyDef = identifier ':' __fre_reference ;

__fre_reference = [ identifier / '.' ]+ ;

// white space and comments
skip WHITE_SPACE = "\\s+" ;
skip SINGLE_LINE_COMMENT = "//[^\\r\\n]*" ;
skip MULTI_LINE_COMMENT = "/\\*[^*]*\\*+(?:[^*/][^*]*\\*+)*/" ;

// the predefined basic types
leaf identifier        = "\`[a-zA-Z0-9-_~!@#$%^&*()+={\\[}\\]|\:;\\"'<>,.?/][a-zA-Z0-9-_~!@#$%^&*()+={\\[}\\]|\:;\\"'<>,.?/]*\`" ;
/* see https://stackoverflow.com/questions/37032620/regex-for-matching-a-string-literal-in-java */
leaf optStringLiteral  = "<no-value>" | stringLiteral ;
leaf stringLiteral     = '"' "[^\\"\\\\]*(\\\\.[^\\"\\\\]*)*" '"' ;
leaf optNumberLiteral  = "<no-value>" | numberLiteral;
leaf numberLiteral     = "[0-9]+";
leaf optBooleanLiteral = "<no-value>" | booleanLiteral;
leaf booleanLiteral    = 'false' | 'true';

}`; // end of grammar
