// Generated by the Freon Language Generator.
// TEMPLATE: SemanticAnalysisTemplate.makeWalker(...)

import {
    type FreNamedNode,
    FreLanguage,
    FreLanguageEnvironment,
    FreNodeReference,
    type FreNode,
    notNullOrUndefined,
    isNullOrUndefined,
} from "@freon4dsl/core";

import { type ProtocolWorker, ProtocolDefaultWorker } from "../utils/index.js";

export class ProtocolSemanticAnalysisWalker extends ProtocolDefaultWorker implements ProtocolWorker {
    changesToBeMade: Map<FreNode, FreNode>;

    constructor(changesToBeMade: Map<FreNode, FreNode>) {
        super();
        this.changesToBeMade = changesToBeMade;
    }

    private findReplacement(node: FreNode, referredElem: FreNodeReference<FreNamedNode>) {
        const scoper = FreLanguageEnvironment.getInstance().scoper;
        const possibles = scoper.getVisibleNodes(node).filter((elem) => elem.name === referredElem.name);
        if (possibles.length > 0) {
            // element probably refers to something with another type
            let replacement: FreNode | undefined = undefined;
            for (const elem of possibles) {
                const metatype = elem.freLanguageConcept();
            }
            if (notNullOrUndefined(replacement)) this.changesToBeMade.set(node, replacement);
        } else {
            // true error, or boolean "true" or "false"
        }
    }
}
