// Generated by the Freon Language Generator.
// TEMPLATE SemanticAnalysisTemplate.makeCorrector(...)

import { type FreLanguageConcept, FreLanguage, type FreNode, FreNodeReference, notNullOrUndefined } from "@freon4dsl/core";

import { ProtocolWalker } from "../utils/index.js";
import { ProtocolSemanticAnalysisWalker } from "./ProtocolSemanticAnalysisWalker.js";

export class ProtocolSemanticAnalyser {
    public correct(modelunit: FreNode) {
        let changesToBeMade: Map<FreNode, FreNode> = new Map<FreNode, FreNode>();
        // create the walker over the model tree
        const myWalker = new ProtocolWalker();

        // create the object that will find what needs ot be changed
        let myCorrector = new ProtocolSemanticAnalysisWalker(changesToBeMade);

        // and add the corrector to the walker
        myWalker.myWorkers.push(myCorrector);

        // do the work
        myWalker.walk(modelunit, () => {
            return true;
        });

        // now change all ref errors
        for (const [toBeReplaced, newObject] of changesToBeMade) {
            const myType: FreLanguageConcept | undefined = FreLanguage.getInstance().concept(toBeReplaced.freLanguageConcept());
            if (notNullOrUndefined(myType)) {
                myType.properties.forEach((prop) => {
                    if (prop.type !== "boolean" && prop.name in toBeReplaced) {
                        // @ts-ignore: if prop.name id present, then it is also present in an object of the same type
                        newObject[prop.name] = toBeReplaced[prop.name];
                    }
                });
                let parent: FreNode = toBeReplaced.freOwnerDescriptor().owner;
                const propName: string = toBeReplaced.freOwnerDescriptor().propertyName;
                const propIndex: number | undefined = toBeReplaced.freOwnerDescriptor().propertyIndex;
                if (notNullOrUndefined(propIndex)) {
                    // @ts-ignore: we are certain that prop.name is present
                    parent[propName].splice(propIndex, 1, newObject);
                } else {
                    // @ts-ignore: we are certain that prop.name is present
                    parent[propName] = newObject;
                }
            }
        }
    }
}
