// Generated by the Freon Language Generator.
// TEMPLATE: ReaderTemplate.generateReader(...)

import { type FreReader, type FreModelUnit, type FreNode, AST, notNullOrUndefined } from "@freon4dsl/core";
import { Protocol } from "../language/index.js";

import { ProtocolGrammarStr } from "./ProtocolGrammar.js";
import { ProtocolSyntaxAnalyser } from "./ProtocolSyntaxAnalyser.js";
import { ProtocolSemanticAnalyser } from "./ProtocolSemanticAnalyser.js";
import {
    Agl,
    type LanguageIssue,
    type LanguageProcessor,
    LanguageProcessorResult,
    type ProcessResult,
    type SentenceContext,
} from "net.akehurst.language-agl-processor";

class MyContext {
    constructor(readonly predefined: Map<string, FreNode>) {}
}

/**
 *   Class ProtocolModelUnitReader is a wrapper that is able to parse all types of
 *   model units in the language.
 */
export class ProtocolModelUnitReader implements FreReader {
    analyser!: ProtocolSyntaxAnalyser;
    parser: LanguageProcessor<Protocol, MyContext> | null | undefined;
    isInitialized: boolean = false;

    initialize() {
        this.analyser = new ProtocolSyntaxAnalyser();
        const res: LanguageProcessorResult<any, any> = Agl.getInstance().processorFromString(
            ProtocolGrammarStr,
            Agl.getInstance().configuration(undefined, (b: any) => {
                b.syntaxAnalyserResolverResult(() => this.analyser);
            }),
        );
        this.parser = res.processor;
        this.isInitialized = true;
    }

    /**
     * Parses and performs a syntax analysis on 'sentence', using the parser and analyser
     * for 'metatype', if available. If 'sentence' is correct, a model unit will be created,
     * otherwise an error wil be thrown containing the parse or analysis error.
     * @param sentence      the input string which will be parsed
     * @param metatype      the type of the unit to be created
     * @param model         the model to which the unit will be added
     * @param sourceName    the (optional) name of the source that contains 'sentence'
     */
    readFromString(sentence: string, metatype: string, model: Protocol, sourceName?: string): FreModelUnit {
        if (!this.isInitialized) {
            this.initialize();
        }
        this.analyser.sourceName = notNullOrUndefined(sourceName) ? sourceName : "";
        let startRule: string = "";
        // choose the correct parser
        if (metatype === "MessageGroup") {
            startRule = "MessageGroup";
        } else if (metatype === "Types") {
            startRule = "Types";
        }

        // parse the input
        let unit: FreModelUnit | null = null;
        if (this.parser) {
            let parseResult: ProcessResult<Protocol> | undefined;
            const options = this.parser.optionsDefault();
            AST.change(() => {
                if (this.parser) {
                    if (startRule.length > 0) {
                        options.parse.goalRuleName = startRule;
                        parseResult = this.parser.process(sentence, options);
                    } else {
                        parseResult = this.parser.process(sentence, null);
                    }
                }
            });
            if (notNullOrUndefined(parseResult)) {
                const errors = parseResult.issues.errors.asJsReadonlyArrayView();
                if (errors.length > 0) {
                    errors.map((err: LanguageIssue) => {
                        // Strip the error message, otherwise it's too long for the webapp,
                        // and add the location information.
                        let location = ` [${sourceName}:${err.location?.line}:${err.location?.column}]`;
                        let mess = err.message.replace(/^Failed to match \{.*?\} at:\s*\.*\s*/, "Parse error: ");
                        // if (!!err.data) {
                        //     mess += ' (expected ' + err.data + ')';
                        // }
                        if (!!mess && mess.length > 0) {
                            // console.log(mess);
                            throw new Error(mess + location);
                        }
                    });
                } else {
                    AST.change(() => {
                        if (notNullOrUndefined(parseResult)) {
                            unit = parseResult.asm as unknown as FreModelUnit;
                        }
                    });
                }
                // do semantic analysis taking into account the whole model, because references could be pointing anywhere
                if (notNullOrUndefined(model)) {
                    try {
                        if (!unit) {
                            throw new Error("Parsing produced no unit.");
                        }
                        const u: FreModelUnit = unit; // cache the narrowed value
                        const name = u.name;
                        if (model.getUnits().some((existing) => existing.name === name)) {
                            throw new Error(`Unit named '${name}' already exists.`);
                        } else {
                            AST.change(() => {
                                model.addUnit(u);
                                const semAnalyser = new ProtocolSemanticAnalyser();
                                semAnalyser.correct(u);
                            });
                        }
                    } catch (e) {
                        console.error(e instanceof Error ? e.message : String(e));
                        throw e;
                    }
                }
            }
            if (!unit) {
                throw new Error("Parsing failed to produce a model unit.");
            }
            return unit;
        } else {
            throw new Error(`No parser for ${metatype} available: grammar incorrect.`);
        }
    }
}
