// Generated by the Freon Language Generator.
import { type KtList, type Sentence, type SpptDataNodeInfo } from "net.akehurst.language-agl-processor";
import { FreNodeReference, notNullOrUndefined } from "@freon4dsl/core";
import { Types, PrimitiveType, ObjectType } from "../language/index.js";
import { PrimValueType, ProtocolSyntaxAnalyser } from "./ProtocolSyntaxAnalyser.js";

export class TypesSyntaxAnalyserPart {
    mainAnalyser: ProtocolSyntaxAnalyser;

    constructor(mainAnalyser: ProtocolSyntaxAnalyser) {
        this.mainAnalyser = mainAnalyser;
    }

    /**
     * Method to transform branches that match the following rule:
     * Types = 'Type' 'Definitions' identifier
     *	 'Primitives:'
     *	 PrimitiveType*
     *	 'Objects:'
     *	 ObjectType* ;
     * @param nodeInfo
     * @param children
     * @param sentence
     */
    public transformTypes(nodeInfo: SpptDataNodeInfo, children: KtList<any>, sentence: Sentence): Types {
        // console.log('4 transformTypes called: ' + children.toString());
        let __name: string;
        let __primitiveTypes: PrimitiveType[];
        let __objectTypes: ObjectType[];
        __name = this.mainAnalyser.transformPrimValue<string>(
            children.asJsReadonlyArrayView()[2] as unknown as string,
            PrimValueType.identifier,
        ); // RHSPrimEntry
        __primitiveTypes = (children.asJsReadonlyArrayView()[4] as KtList<any>).asJsReadonlyArrayView() as PrimitiveType[]; // RHSPartListEntry
        __objectTypes = (children.asJsReadonlyArrayView()[6] as KtList<any>).asJsReadonlyArrayView() as ObjectType[]; // RHSPartListEntry

        return Types.create({
            name: __name!,
            primitiveTypes: __primitiveTypes!,
            objectTypes: __objectTypes!,
            parseLocation: this.mainAnalyser.location(sentence, nodeInfo.node),
        });
    }

    /**
     * Method to transform branches that match the following rule:
     * PrimitiveType = 'primitive' identifier ':' stringLiteral ;
     * @param nodeInfo
     * @param children
     * @param sentence
     */
    public transformPrimitiveType(nodeInfo: SpptDataNodeInfo, children: KtList<any>, sentence: Sentence): PrimitiveType {
        // console.log('4 transformPrimitiveType called: ' + children.toString());
        let __name: string;
        let __primitiveType: string;
        __name = this.mainAnalyser.transformPrimValue<string>(
            children.asJsReadonlyArrayView()[1] as unknown as string,
            PrimValueType.identifier,
        ); // RHSPrimEntry
        __primitiveType = this.mainAnalyser.transformPrimValue<string>(
            children.asJsReadonlyArrayView()[3] as unknown as string,
            PrimValueType.string,
        ); // RHSPrimEntry

        return PrimitiveType.create({
            name: __name!,
            primitiveType: __primitiveType!,
            parseLocation: this.mainAnalyser.location(sentence, nodeInfo.node),
        });
    }
}
