// Generated by the Freon Language Generator.
// TEMPLATE: CommandLineTemplate.generateCommandLineRunner()
// Run this as the main program.

import { LanguageEnvironment } from "../index.js";

import { FreonCommandLine } from "./gen/FreonCommandLine.js";
import { DummyAction } from "./gen/DummyAction.js";

// ensure language is initialized
const tmp = LanguageEnvironment.getInstance();

// Create the command line object
const cli: FreonCommandLine = new FreonCommandLine();

// Add specific actions to the command line tool
// REPLACE WITH YOUR OWN
cli.addAction(new DummyAction());

// Run it
cli.executeAsync();
